all : 
	make all -C ./philo
	make all -C ./philo_bonus

clean :
	make clean -C ./philo
	make clean -C ./philo_bonus

fclean :
	make fclean -C ./philo
	make fclean -C ./philo_bonus

re :
	make re -C ./philo
	make re -C ./philo_bonus
